### ISSUE TITLE
1.1.43 rollback?

### ISSUE THREAD

**Issue by Commifreak** [protectli-root/protectli-firmware-updater#39]
It seems 1.1.43 got rolled back? Why?

https://github.com/protectli-root/protectli-firmware-updater/commit/97faba871a53bd2e98c69efdb3cbf7f3ce1ca0c0

**Comment by SergeyKonst3** [comment]
Yes, 1.1.43 got rolled back. Version 1.1.43 included coreboot for the V1210, however, we found a possible issue and decided to do a roll back.

We are seeing unexpected behavior in regards to the Intel ME. The issue is being investigated, once it is resolved we will release coreboot for the V1210.

I apologize for any inconvenience.
